import { useState } from 'react';
import { Link, useLocation, useParams } from 'wouter';
import { Bookmark, BookmarkCheck, ChevronLeft, Play } from 'lucide-react';
import { videos } from '../data/mock';
import { EmptyState, Eyebrow, PageHeading, Thumb, VideoCard, VideoCompact } from '../components/SignalUI';

type VideoProps={saved:string[];toggle:(id:string)=>void;watched:string[];toggleWatched:(id:string)=>void};
export function VideosPage({saved,toggle,watched,toggleWatched}:VideoProps) {
  const [filter,setFilter]=useState('All');
  const filtered=videos.filter(v=>filter==='All'||(filter==='Unwatched'?!watched.includes(v.id):saved.includes(v.id)));
  return <><PageHeading eyebrow="Watch on your terms" title="Video library" description="Recent work from the channels you follow. Pick a thread and take your time."/><div className="mb-7 flex items-center justify-between border-b border-border pb-4"><div className="flex gap-2">{['All','Unwatched','Saved'].map(x=><button key={x} onClick={()=>setFilter(x)} className={`border-b-2 px-2 py-2 text-[11px] ${filter===x?'border-primary text-foreground':'border-transparent text-muted-foreground hover:text-foreground'}`} data-testid={`filter-videos-${x.toLowerCase()}`}>{x}</button>)}</div><span className="text-[11px] text-muted-foreground">{filtered.length} videos</span></div>{filtered.length?<div className="grid gap-x-6 gap-y-8 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(v=><VideoCard key={v.id} video={v} saved={saved.includes(v.id)} toggle={()=>toggle(v.id)} watched={watched.includes(v.id)} toggleWatched={()=>toggleWatched(v.id)}/>)}</div>:<EmptyState title={filter==='Saved'?'Nothing saved here yet':'You are all caught up'} text={filter==='Saved'?'Bookmark a video and it will be waiting here.':'New videos from your channels will appear here.'} action={filter==='Saved'?<button onClick={()=>setFilter('All')} className="text-primary" data-testid="button-browse-videos">Browse all videos</button>:undefined}/>}</>;
}

export function VideoPage({saved,toggle,watched,toggleWatched}:VideoProps) {
  const params=useParams<{videoId:string}>();
  const video=videos.find(v=>v.id===params.videoId);
  const [,setLocation]=useLocation();
  if(!video)return <EmptyState title="Video not found" text="This video is no longer in your library." action={<Link href="/videos" className="text-primary">Back to videos</Link>}/>;
  return <div className="mx-auto max-w-[920px]"><button onClick={()=>setLocation('/videos')} className="mb-6 inline-flex items-center gap-1 text-[11px] text-muted-foreground hover:text-primary" data-testid="button-back-videos"><ChevronLeft size={14}/>Back to video library</button><div className="grid gap-7 lg:grid-cols-[minmax(0,1fr)_235px]"><div><div className="relative"><Thumb video={video} large/><div className="absolute inset-0 grid place-items-center"><span className="grid h-14 w-14 place-items-center rounded-full border border-white/70 bg-black/20 text-white"><Play size={20} fill="currentColor"/></span></div><span className="absolute bottom-3 right-3 bg-black/70 px-2 py-1 text-[10px] text-white">Preview player · fictional</span></div><div className="mt-6 flex items-start justify-between gap-4"><div><Eyebrow>{video.channel} · {video.category}</Eyebrow><h1 className="serif mt-2 text-[35px] leading-[1.1] md:text-[42px]" data-testid="heading-video">{video.title}</h1><p className="mt-3 text-[11px] text-muted-foreground">Published {video.publishedAt} · {video.duration}</p></div><button onClick={()=>toggle(video.id)} className="flex shrink-0 items-center gap-2 border border-border px-3 py-2 text-[11px] hover:border-primary" data-testid="button-save-video-detail">{saved.includes(video.id)?<BookmarkCheck size={15}/>:<Bookmark size={15}/>}<span className="hidden sm:inline">{saved.includes(video.id)?'Saved':'Save'}</span></button></div><p className="mt-6 max-w-[680px] text-[13px] leading-7 text-muted-foreground">A thoughtful conversation from {video.channel} exploring {video.title.toLowerCase()}. This is a fictional preview for your personal library; no external video is embedded.</p></div><aside className="border-t border-border pt-4 lg:border-t-0 lg:border-l lg:pl-6"><Eyebrow>Your progress</Eyebrow><button onClick={()=>toggleWatched(video.id)} className="mt-4 flex w-full items-center justify-between border border-border px-3 py-3 text-left text-[12px] hover:border-primary" data-testid="button-watched-detail"><span>{watched.includes(video.id)?'Watched':'Mark as watched'}</span><span className={`h-4 w-4 rounded-full border ${watched.includes(video.id)?'border-primary bg-primary':'border-muted-foreground'}`}/></button><p className="mt-3 text-[11px] leading-5 text-muted-foreground">Your watch status stays on this device.</p></aside></div><div className="mt-11 border-t border-border pt-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-[11px] font-semibold uppercase tracking-[.13em]">Up next from your follows</h2><Link href="/videos" className="text-[11px] text-primary">All videos</Link></div><div className="grid gap-4 sm:grid-cols-2">{videos.filter(v=>v.id!==video.id).slice(0,2).map(v=><VideoCompact key={v.id} video={v} saved={saved.includes(v.id)} toggleSave={()=>toggle(v.id)} watched={watched.includes(v.id)} toggleWatched={()=>toggleWatched(v.id)}/>)}</div></div></div>;
}